language: python
python: 2.7
sudo: false
cache:
  directories:
  - eggs
env:
  matrix:
  - PLONE_VERSION=4.2
matrix:
  include:
  - python: 2.6
    env: PLONE_VERSION=4.1
  fast_finish: true
install:
- sed -ie "s#test-4.2#test-$PLONE_VERSION#" buildout.cfg
- sed -ie "s#versions-4.2#versions-$PLONE_VERSION#" buildout.cfg
- python bootstrap.py
- bin/buildout annotate
- bin/buildout
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
script:
- test $PLONE_VERSION != 4.1 && bin/code-analysis || true
- bin/test
after_success:
- bin/createcoverage
- pip install coveralls
- coveralls
notifications:
  irc: irc.freenode.org#plone-testing
